#44 - Change GCS naming scheme
ARCOMM/ARCHUB pull request #108
Opened 2021-08-06 19:57 UTC by TomBurch

2021-08-06 20:17 UTC, WirelessPillow requested changes
Revision is added at the end of map name, please adjust so the revision portion is after the file name but prior to the .map name

2021-08-06 20:47 UTC, WirelessPillow approved these changes

2021-08-06 20:48 UTC, WirelessPillow commented
Please don't complete the merger till Sunday

2021-08-08 17:09 UTC, BorderKeeper approved these changes
lgtm

2021-08-08 17:11 UTC, merged